### PR TITLE
Cleanup and validate Mesos Master URLs during startup

### PR DESCRIPTION
**Pull request by andygrunwald**
When i launched complainer the first time, i made a few mistakes and assigned wrong IPs and so on. And i saw messages like:

```
I0615 13:31:10.053617  5474 exec.cpp:143] Version: 0.28.1
I0615 13:31:10.056813  5478 exec.cpp:217] Executor registered on slave e739267b-454f-4b63-82ba-c9918a4eae07-S0
WARNING: Your kernel does not support memory limit capabilities. Limitation discarded.
2016/06/15 13:31:10 Error fetching state from http://192.168.2.127:5050/: Get http://10.2.2.127:5050//master/state: dial tcp 192.168.2.127:5050: getsockopt: connection refused
2016/06/15 13:31:10 Error fetching state from http://10.2.2.126:5050/: Get http://10.2.2.126:5050//master/state: dial tcp 192.168.2.126:5050: getsockopt: connection refused
2016/06/15 13:31:10 Error fetching state from http://10.2.2.124:5050/: Get http://10.2.2.124:5050//master/state: dial tcp 192.168.2.124:5050: getsockopt: connection refused
2016/06/15 13:31:10 mesos master not found
```

Especially urls like `http://10.2.2.127:5050//master/state`.
I had a look and i saw that Master URLs are not cleaned and validated. This PR offers basic validation in two parts:
1. Ensure that the URL is parsable at all
2. Remove the last `/` if the URL has one

The last `/` will be removed, because complainer just add the path. See https://github.com/cloudflare/complainer/blob/master/mesos/cluster.go#L43

A simple and isolated clean url test can be found here: https://play.golang.org/p/A0dtk50Zk5

A few examples:
```
$ ./complainer -masters "://fofofo.org" -uploader noop -reporters slack
2016/06/16 15:39:29 One of your entered Mesos master can't be parsed as a URL: parse ://fofofo.org: missing protocol scheme

$ ./complainer -masters " " -uploader noop -reporters slack
2016/06/16 15:43:58 After URL cleanup, there is no Mesos master left over. Please check -masters argument

./complainer -masters " , ://test, , , " -uploader noop -reporters slack
2016/06/16 15:44:37 One of your entered Mesos master can't be parsed as a URL: parse ://test: missing protocol scheme
```

### CODE REVIEW

**Comment by bobrik** [comment]
A few notes:

* Please use `'`, not `.
* `if strings.HasSuffix(s, "/") { s = s[0 : len(s)-1] }` can be replaced with `strings.TrimSuffix(s, "/")`
* There's no reason to tolerate a single invalid URL.

Given that `lol` is a parseable URL, I don't know if it's worth checking during start up. I was thinking about doing a few retries in Mesos code and failing if Mesos is unavailable X times in a row.

https://github.com/mesosphere/mesos_exporter/pull/8/files

**Comment by andygrunwald** [comment]
I fixed all three points you mentioned. I only check if `len(masterList) > 0`.
Indeed, `lol` is a parseable url.

The `errorCounter.Inc()` from mesos_exporter PR is, indeed, a good solution for the runtime.
Checking basic `url.Parse` will not hurt and catches initial user errors. IMO both solutions add value to each other. If an URL is not parsable, you don`t run into (unnecessary) request errors during runtime.

Anyway, what do you suggest? Drop this PR at all? Remove the `url.Parse` and only apply `strings.TrimSuffix`? Or merge complete?
I am open to everything.

**Comment by bobrik** [comment]
I think doing just `strings.TrimSuffix` in `mesos/cluster.go` should do the job. Once health check endpoint is in, it will be responsible for catching inaccessible Mesos URLs.

**Comment by andygrunwald** [comment]
@bobrik Done.
A cleaner way would be the `TrimSuffix` in `NewCluster`, then you know you have a clean list of masters. Now, every poll it will be repeated (the trim). Should i change it?

**Comment by bobrik** [comment]
Yeah, let's trim it in `NewCluster`. Can you also squash everything into a single commit?

**Comment by andygrunwald** [comment]
Gimme a few more minutes / hours and i will do this, this can be go (maybe) in the next release. Fine for you?

**Comment by bobrik** [comment]
Sure

**Comment by andygrunwald** [comment]
See #39

**Pull request closed without merging**
